language: java
jdk:
    - openjdk7
    - oraclejdk7

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CM1oXCMVdXPob4BprqapZdoybbWxV7AQo3gT0xLiXqS11bCzh+h9j62bJzY6OV3/04Ii+7yTgh51QBlhbI7pVZ+uicntsd+BcOX2f8iYdgfy9guZW/OSUrG3gk1Y6e0hQdzlN6s6d1y2Te5rEeX8pcopFfPlCfpvzsfMo6Pj2V4="

addons:
  coverity_scan:
    project:
      name: "Gustorn/softlab4"
      description: "Build submitted via Travis CI"
    notification_email: gustorn@gmail.com
    build_command_prepend: "gradle clean"
    build_command:   "gradle build"
    branch_pattern: coverity_scan
