language: java
jdk:
    - openjdk7
    - oraclejdk7
    - openjdk6
install:
  - sudo apt-get update
  - sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended
before_script:
  - bash build_docs.sh
