language: java
jdk:
    - openjdk7
    - oraclejdk7
    - openjdk6
install:
  - sudo apt-get update
  - sudo apt-get upgrade --assume-yes
  - sudo apt-get install texlive-latex-base --assume-yes
before_script:
  - bash build_docs.sh
